server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://134.175.142.230:3306/weblog?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Sans-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /swagger-ui.html/**,/v2/api-docs,/webjars/**,/swagger-resources/**,/v2/**

mybatis-plus:
  mapper-locations: classpath:mappers/*/*.xml
  #configuration:
    #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#是否开启 swagger-ui
swagger:
  enabled: true

# 文件存储路径
file:
  path: \sru
  avatar: \sru
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
